name: Feedback
labels: ["Feedback"]
description: | 
  Open a PBI based on feedback from clients.
body:
  - type: markdown
    attributes:
      value: |
        **Reminder:**
        - Select milestone
        - Fill out all the fields after you submit
  - type: input
    id: feedback-from
    attributes:
      label: Who is the feedback from
      description: Write who the stakeholder is and their name
      placeholder: Stakeholder - Name
    validations:
      required: true  

  - type: input
    id: feedback-date
    attributes:
      label: Date Received
      description: When was this feedback received?
      placeholder: DD/MM
      
  - type: textarea
    id: description
    attributes:
      label: Whats the feedback
      description: Describe the feedback given
      placeholder: |
        Be detailed.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Describe the feedback and how would this be implemented.
      placeholder: |
        Description
        - [ ] Criteria 1
        - [ ] Criteria 2
      value: |
        - [ ] 
        - [ ] 
    validations:
      required: true
