name: Backlog Iteam
description: Write each backlog item as an Issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all sections before submitting.
  - type: input
    id: story-points
    attributes:
      label: Story Points
      description: Estimate the effort
      placeholder: 1-10
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Bug
        - Feature
        - Improvement
        - Question
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the issue
      placeholder: Describe what the issue is and how to reproduce it
    validations:
      required: true
