name: Backlog Item
description: | 
  **ATTENTION:** Search for existing issues before creating a new one. PREVENT DUPLICATION.
body:
  - type: markdown
    attributes:
      value: |
        **Reminder:**
        - Use labels!
        - Select milestone 
        - Fill out all the sections
  - type: input
    id: story-points
    attributes:
      label: Story Points
      description: Estimate the effort
      placeholder: 1-10
    validations:
      required: true  
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      description: Describe how you plan to implement this feature.
      placeholder: |
        - Describe the logic
        - Mention components or files involved

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for this to be considered done.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true
