name: Backlog Iteam
description: Write each backlog item as an Issue
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all sections before submitting.
  - type: input
    id: story-points
    attributes:
      label: Story Points
      description: Estimate the effort
      placeholder: 1-10
    validations:
      required: true  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      description: Describe how you plan to implement this feature.
      placeholder: |
        - Describe the logic
        - Mention components or files involved
      value: |
        <!-- Provide a clear technical approach -->

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for this to be considered done.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      value: |
        - [ ] The feature must do X
        - [ ] Edge case Y is handled
        - [ ] Tested and documented
    validations:
      required: true
